use retail;

select * from customer;

select * from orders;

select * from purchase;

ALTER TABLE customer
ALTER COLUMN customer_id INT NOT NULL;

ALTER TABLE customer
ADD CONSTRAINT PK_customer PRIMARY KEY (customer_id);

ALTER TABLE orders
ALTER COLUMN order_id INT NOT NULL;

ALTER TABLE orders
ADD CONSTRAINT PK_orders PRIMARY KEY (order_id);



alter table orders
add constraint FK_orders_customer foreign key (customer_id) references customer(customer_id);

alter table purchase
alter column order_id int;



alter table purchase
add constraint fk_purchase_orders foreign key (order_id) references orders(order_id);

alter table purchase
alter column customer_id int;

alter table purchase
add constraint fk_purchase_customer foreign key (customer_id) references customer(customer_id);



-- Task 1:
-- Customer Orders Count
-- Find the total number of orders placed by each customer, show customer name and their order count.

select c.customer_name, count(o.order_id) as Total_orders from customer c
join orders o on c.Customer_ID = o.Customer_ID
group by c.Customer_name;


-- Task 2: 
-- High Value Orders
-- Find all orders where the total purchase amount is greater than 3000, show order id, customer id and amount.

select order_id, customer_id, Total_purchase_Amount as Amount from Purchase
where Total_purchase_Amount > 3000;


--Task 3:
-- Revenue by Payment Method
-- Find the total revenue generated by each payment method (Cash, PayPal, Credit Card).

select Payment_method, sum(Total_purchase_Amount) as Total_Revenue from purchase
group by Payment_method;


-- Task 4:
-- Returned Orders
--  Find all orders that were returned (return_order = 1), show customer name and purchase amount.

select c.customer_name, p.Total_purchase_Amount as Amount from customer c
join purchase p on p.Customer_ID = c.Customer_ID
where Returns = 1;


-- Task 5:
-- Determine the most popular payment method specifically among female customers.

select top 1 p.Payment_Method from purchase p
join customer c on p.Customer_ID = c.Customer_ID
where Gender = 'Female'
group by p.Payment_Method
order by count(p.Payment_Method) desc;

-- Task 6:
-- Find the total revenue grouped by year and month to identify the highest-grossing month in the store's history.

SELECT 
    YEAR(Purchase_Date) AS sales_year, 
    MONTH(Purchase_Date) AS sales_month, 
    SUM(Total_Purchase_Amount) AS monthly_revenue 
FROM purchase
GROUP BY YEAR(Purchase_Date), MONTH(Purchase_Date)
ORDER BY monthly_revenue DESC;

-- Task 7:
-- Find the names of customers who have made at least one purchase that was strictly higher than the average purchase amount across the entire store.

SELECT DISTINCT 
    c.Customer_Name 
FROM customer c
JOIN purchase p ON c.Customer_ID = p.Customer_ID
WHERE p.Total_Purchase_Amount > (
    SELECT AVG(Total_Purchase_Amount) FROM purchase
);

